[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npx prisma migrate deploy --schema=src/db/prisma/schema.prisma; npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
